<?php
/**
 *
 * @link       laserwp.com/contact
 * @since      1.0.0
 * @package    core
 * @subpackage core/
 * @author     Laser WordPress Team <contact@laserwp.com>
 */

namespace Lwwb\Base\CPT;

class CPT_External_Post extends CPT_Base {

	public $post_type = 'lwwb_external_post';

	public function register() {
		$this->ctp = $this->set_post_type();
		parent::register(); // TODO: Change the autogenerated stub
	}

	public function set_post_type() {

		$labels = array(
		);

		$arg = array(
			'labels'              => $labels,
			'public'              => false,
			'rewrite'             => false,
			'show_ui'             => false,
			'show_in_menu'        => false,
			'show_in_nav_menus'   => false,
			'show_in_rest'        => true,
			'exclude_from_search' => true,
			'can_export'          => true,
			'_builtin'            => true, /* internal use only. don't use this when registering your own post type. */
			'supports'            => array( 'title', 'revisions' ),
			'capability_type'     => 'post',
			'show_in_quick_edit'  => false,
			'hierarchical'        => false,
		);

		return $arg;
	}
}